require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'Firebase', :modular_headers => true # add firebase
pod 'FirebaseCore', :modular_headers => true  # add firebase
pod 'GoogleUtilities', :modular_headers => true  # add firebase
$RNFirebaseAsStaticFramework = true  # add firebase
platform :ios, '11.0'

target 'ChileeApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
#  use_frameworks! :linkage => :static   # add firebase
  target 'ChileeAppTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
